stages:
  - build
  - migrate
  - deploy

variables:
  # SERVICE
  SERVICE: ppi-api-fm

  # HARBOR
  HARBOR_HOST: "10.14.204.78:80"
  HARBOR_USERNAME: "admin"
  HARBOR_PASSWORD: "P@ssw0rdNyaHarbor#5757"

  # DOCKER
  DOCKER_IMAGE: $HARBOR_HOST/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

default:
  tags:
    - shell

build:
  stage: build
  before_script:
    - docker login $HARBOR_HOST -u $HARBOR_USERNAME -p $HARBOR_PASSWORD
    # Pre-pull base images jika tidak tersedia di local storage runner
    - docker image inspect mcr.microsoft.com/dotnet/sdk:10.0 > /dev/null 2>&1 || docker pull mcr.microsoft.com/dotnet/sdk:10.0
    - docker image inspect mcr.microsoft.com/dotnet/aspnet:10.0 > /dev/null 2>&1 || docker pull mcr.microsoft.com/dotnet/aspnet:10.
  script:
    # - docker build --no-cache -t $DOCKER_IMAGE -f Dockerfile .
    - docker build -t $DOCKER_IMAGE -f Dockerfile .
    - docker push $DOCKER_IMAGE
  only:
    - main
    - staging

deploy_development:
  stage: deploy
  before_script:
    - export KUBECONFIG=~/.kube/k8s-staging
  script:
    - kubectl set image deployment/$SERVICE $SERVICE=$DOCKER_IMAGE -n development
    - kubectl rollout restart deploy/$SERVICE -n development
  only:
    - main

deploy_staging:
  stage: deploy
  before_script:
    - export KUBECONFIG=~/.kube/k8s-staging
  script:
    - kubectl set image deployment/$SERVICE $SERVICE=$DOCKER_IMAGE -n staging
    - kubectl rollout restart deploy/$SERVICE -n staging
  only:
    - staging
  when: manual